### ISSUE TITLE
请教你下的你blog服务器是用的哪家的?

### ISSUE THREAD

**Issue by brooklee33** [gzdaijie/koa-react-server-render-blog#1]
你好，看你的 http://imtuzi.com/ 这个 blog 服务器显示ip是日本的，感觉速度很快! 请问一下使用的哪家的服务器？谢谢！

**Comment by geektutu** [comment]
租用的是腾讯云 1M1G的服务器。ip显示日本的话，估计是腾讯云内网ip使用了公网ip的原因。
速度快是因为我做了一些优化
1. 静态文件缓存
2. 保证每个页面不超过50K，因为我的下载带宽只有128K，1s内加载完成，必须要小于100K 
3. mongdb数据库，目前文章比较少，随意没做优化，这一块也可以考虑用内存做缓存。

**Comment by brooklee33** [comment]
谢谢！
