### ISSUE TITLE
站点Header需要改ejs才能替换

### ISSUE THREAD

**Issue by Songziyuan** [gzdaijie/koa-react-server-render-blog#72]
如图，极客兔兔生成的站点，只能修改heade.ejs才能替换这个title，能否读取config目录下的title呢？
<img width="712" alt="Screen Shot 2019-07-11 at 17 11 28" src="https://user-images.githubusercontent.com/15028748/61038191-28eb2d80-a3ff-11e9-9bf1-ebcf863716b9.png">
<img width="1028" alt="Screen Shot 2019-07-11 at 17 10 43" src="https://user-images.githubusercontent.com/15028748/61038194-2a1c5a80-a3ff-11e9-8f6a-4797df93976c.png">

**Comment by geektutu** [comment]
感谢提bug，今晚修复！

**Comment by geektutu** [comment]
感谢提醒，这个问题已经修复。
