### ISSUE TITLE
Github Pages编译失败

### ISSUE THREAD

**Issue by Yikhan** [gzdaijie/koa-react-server-render-blog#74]
deploy到gitpage之后一直收到报错：

> The page build failed for the `master` branch with the following error:
The tag `{%` on line 135 in `themes/geektutu/layout/post.ejs` was not properly closed with `%}`. For more information, see https://help.github.com/en/articles/page-build-failed-tag-not-properly-terminated.

感觉不应该是这个文件的问题，不知道是哪里没有配置好。
另外我是用git submodule来引入themes/geektutu的。

我的[repo](https://github.com/Yikhan/Blog/tree/master)

**Comment by geektutu** [comment]
先 yarn build，再 yarn deploy。
另外，我看了你的repo，我做了很多的功能，需要在 _config.xml 里配置一些信息，你可以参考 [README.md](https://github.com/geektutu/hexo-theme-geektutu/blob/master/README.md) 进行配置，也可以参考我现在运行着的博客的 [_config.xml](https://github.com/geektutu/geektutu-blog/blob/master/_config.yml)

**Comment by Yikhan** [comment]
感谢回复

我是按照文档的步骤来的，重新新建了一个项目后编译可以通过了，可能第一次初始化git配置的时候没弄好，特别是开始的时候没有使用submodule来加载theme模板，导致git出现嵌套问题（blog项目本身是一个repo，clone下来的模板也是一个repo），一直收到github发来的报错邮件。

参考了其他博客主的掉坑经验才发现要用git submodule add命令来代替clone
https://blog.junyu.io/posts/0003-choose-a-theme-you-like.html

希望对后来碰到类似问题的朋友有所帮助。
