### ISSUE TITLE
header_img的作用

### ISSUE THREAD

**Issue by Yikhan** [gzdaijie/koa-react-server-render-blog#75]
请问_config.yml中的header_img用于设置哪里的图片呢？

我一开始以为是博客上方head的背景图片，但发现模版代码里面似乎已经用css自带的颜色写死了。设置了header_img后也没有发现任何地方有变化。

**Comment by geektutu** [comment]
这个没用了，原来最上面背景是一张大图，可配置的。后来改设计了，变窄了，觉得纯色更清爽一点。有时间我更新下文档。
