### ISSUE TITLE
关于专栏或者说专题实现

### ISSUE THREAD

**Issue by xdmdcp** [gzdaijie/koa-react-server-render-blog#78]
我想问一下具体是怎么生成，是需要自己手动排版吗？我看了一下你的博客仓库，没有发现怎么生成这个的步骤。希望你有空公知一下。十分感谢。

**Comment by geektutu** [comment]
```bash
---
title: 动手写ORM框架 - GeeORM第一天 database/sql 基础
date: 2020-03-07 23:00:00
description: ...
nav: 从零实现
categories:
- ORM框架 - GeeORM
image: post/geeorm/geeorm_sm.jpg
---
```

专题复用的是 categories 的配置，和其他主题是没有区别的。

唯一的区别在于专题太多的时候，顶部展示不下，可以用 nav 折叠，多个专题如果配置了相同的 nav，则会以下拉框的形式出现。

**Comment by xdmdcp** [comment]
> ```shell
> ---
> title: 动手写ORM框架 - GeeORM第一天 database/sql 基础
> date: 2020-03-07 23:00:00
> description: ...
> nav: 从零实现
> categories:
> - ORM框架 - GeeORM
> image: post/geeorm/geeorm_sm.jpg
> ---
> ```
> 
> 专题复用的是 categories 的配置，和其他主题是没有区别的。
> 
> 唯一的区别在于专题太多的时候，顶部展示不下，可以用 nav 折叠，多个专题如果配置了相同的 nav，则会以下拉框的形式出现。

好的，感谢解答。另外有个问题，关于专题的排序是按照文章时间排序，还是说可以自定义专题的顺序。举个例子，例如想把杂谈放到最右边。需要如何实现？

**Comment by geektutu** [comment]
按时间顺序，不支持自定义顺序。

**Comment by xdmdcp** [comment]
十分感谢，可能我问题有点多，麻烦到你了。还有最后一个问题。
我想**related_links哪里加个邮箱图标，然后点击实现跳转邮箱的功能**，大概是这个网站的功能。https://bbruceyuan.github.io/

**Comment by geektutu** [comment]
@YuJian95 链接填 `mailto` 加邮箱地址就好了，你可以搜索下，具体怎么写的忘了。

**Comment by xdmdcp** [comment]
好的，感谢解答。@geektutu
