### ISSUE TITLE
tool/comments.json 服务器上显示No such file or directory错误

### ISSUE THREAD

**Issue by kaige86** [gzdaijie/koa-react-server-render-blog#82]
https://github.com/geektutu/hexo-theme-geektutu/blob/8da143bb1eed54224d2fca57111ce0a73abfa22a/layout/_widget/comments.ejs#L74

GET /tool/comments.json  HTTP/1.1
tool/comments.json文件找不到

**Comment by geektutu** [comment]
这个是为了没有评论的时候，显示跳转到 Github 的按钮用的。我在服务器上部署了一个脚本生成这个对应关系 [comments.js](https://github.com/geektutu/geektutu-blog/blob/master/myscripts/comments.js)，也可以 touch 一个空文件解决。
